disp(['Add the paths of the different toolboxes... '])
addpath('../Diagnostic_tools')
addpath('../Tides')
addpath('../Preprocessing_tools')
addpath('../Visualization_tools')
addpath('../Nesting_tools')
addpath('../m_map')
addpath('../netcdf_matlab')
addpath('../netcdf_matlab/ncfiles')
addpath('../netcdf_matlab/nctype')
addpath('../netcdf_matlab/ncutility')
addpath('../mask')
addpath('../SST_pathfinder')
addpath('../Bulk_forcing')
